In [3]:
#to import datasets
from sklearn import datasets
dir(datasets)
from sklearn.datasets import load_iris
iris=load_iris()
dir(iris)
iris.target_names
iris.feature_names

#to check data shape (rows & columns)
iris.data.shape

iris.target.shape

iris.target.size


150

In [8]:
#!/usr/bin/python3

from sklearn.datasets import load_iris

#loading all data
iris=load_iris()

#printing feature name
print(iris.feature_names)

#target names
print(iris.target_names)

#training data (to see the data)
print(iris.data)

#target data means flower data
print(iris.target)


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3

In [22]:
##training&testing

#!/usr/bin/python3

#import numpy
from sklearn.datasets import load_iris

#loading all data
iris=load_iris()

#printing feature name
#print(iris.feature_names)

#target names
#print(iris.target_names)

#only setosa
#setosa=iris.data[0:50]

#to print data 1-by-1

#only setosa data
s_data = iris.target[0:50]
print(s_data)
print(s_data.size)

#only versicolor data
v_data = iris.target[50:100]
print(v_data)
print(v_data.size)

#only virginica data
vir_data = iris.target[100:150]
print(vir_data)
print(vir_data.size)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
50
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
50
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
50


In [28]:
##training&testing
#splitting data on percentage basis (to print all data)

#!/usr/bin/python3


import numpy
from sklearn.datasets import load_iris

#loading all data
iris=load_iris()

#printing feature name
print(iris.feature_names)

#target names
print(iris.target_names)

#data position which you want to delete (for testing purpose)
x=[0,50,100]

only_target_training=numpy.delete(iris.target,x)
only_data_training=numpy.delete(iris.data,x,axis=0)
#target data role
print(only_target_training.size)
print(only_data_training)

#testing target
test_target=iris.target[x]
test_data=iris.data[x]
print(test_target)
print(test_data)



['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
147
[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4

In [36]:
## applying DecisionTree algo

#!/usr/bin/python3

import numpy
from sklearn import tree
from sklearn.datasets import load_iris

#loading all data
iris=load_iris()

#printing feature name
print(iris.feature_names)

#target names
print(iris.target_names)

#data position which you want to delete (for testing purpose)
x=[0,50,100]

only_target_training=numpy.delete(iris.target,x)
only_data_training=numpy.delete(iris.data,x,axis=0)
#target data role
print(only_target_training.size)
print(only_data_training)

#testing target
test_target=iris.target[x]
test_data=iris.data[x]
print(test_target)
print(test_data)


#calling algo

clf=tree.DecisionTreeClassifier()
trained=clf.fit(only_data_training, only_target_training)
output=trained.predict([[7,3.2,4.7,1.4]])
print(output)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
147
[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4

In [ ]:
## creating graph


#!/usr/bin/python3
import matplotlib.pyplot as plt
import numpy
from sklearn import tree
from sklearn.datasets import load_iris

#loading all data
iris=load_iris()

#printing feature name
print(iris.feature_names)

#target names
print(iris.target_names)

#data position which you want to delete (for testing purpose)
x=[0,50,100]

only_target_training=numpy.delete(iris.target,x)
only_data_training=numpy.delete(iris.data,x,axis=0)
#target data role
print(only_target_training.size)
print(only_data_training)

#testing target
test_target=iris.target[x]
test_data=iris.data[x]
print(test_target)
print(test_data)


#calling algo

clf=tree.DecisionTreeClassifier()
trained=clf.fit(only_data_training, only_target_training)
output=trained.predict([[7,3.2,4.7,1.4]])
print(output)


#making cahrts
